import type { DebrisData, ThreatData, ProximityThreat, SignalThreat, AnomalyThreat, OrbitalSimilarityThreat } from "@/types"

// NOTE: All satellite data comes from the Space-Track backend via /api/satellites.
// The SJ-26 demo scenario satellite is injected via demo-trajectories.ts.
// No hardcoded satellite list — MOCK_SATELLITES has been removed.

/**
 * Generate 2500 random debris objects in LEO.
 */
export function generateMockDebris(count: number = 2500): DebrisData[] {
  const debris: DebrisData[] = []
  for (let i = 0; i < count; i++) {
    const lat = (Math.random() - 0.5) * 160 // -80 to 80
    const lon = (Math.random() - 0.5) * 360 // -180 to 180
    const altKm = 200 + Math.random() * 1800 // 200-2000 km LEO
    debris.push({
      noradId: 90000 + i,
      lat,
      lon,
      altKm,
    })
  }
  return debris
}

export const MOCK_THREATS: ThreatData[] = [
  {
    id: "threat-1",
    primaryId: "sat-6",
    secondaryId: "debris-1201",
    primaryName: "USA-281",
    secondaryName: "COSMOS 2251 DEB",
    severity: "threatened",
    missDistanceKm: 0.8,
    tcaTime: Date.now() + 1200000,
    tcaInMinutes: 20,
    primaryPosition: { lat: 35.2, lon: -42.8, altKm: 500 },
    secondaryPosition: { lat: 35.5, lon: -42.3, altKm: 502 },
    intentClassification: "Uncontrolled debris",
    confidence: 0.95,
  },
  {
    id: "threat-2",
    primaryId: "sat-14",
    secondaryId: "unknown-1",
    primaryName: "WGS-10",
    secondaryName: "UNKNOWN OBJ 4718",
    severity: "watched",
    missDistanceKm: 12.4,
    tcaTime: Date.now() + 3600000,
    tcaInMinutes: 60,
    primaryPosition: { lat: -0.1, lon: 78.5, altKm: 35786 },
    secondaryPosition: { lat: -0.2, lon: 79.2, altKm: 35790 },
    intentClassification: "Maneuvering — intent unclear",
    confidence: 0.62,
  },
  {
    id: "threat-3",
    primaryId: "sat-1",
    secondaryId: "debris-0442",
    primaryName: "ISS (ZARYA)",
    secondaryName: "FENGYUN 1C DEB",
    severity: "nominal",
    missDistanceKm: 85.0,
    tcaTime: Date.now() + 7200000,
    tcaInMinutes: 120,
    primaryPosition: { lat: 48.7, lon: 12.3, altKm: 408 },
    secondaryPosition: { lat: 49.1, lon: 13.0, altKm: 415 },
    intentClassification: "Uncontrolled debris",
    confidence: 0.88,
  },
]

// ── Proximity Inspection & Attack Positioning ──

export const MOCK_PROXIMITY_THREATS: ProximityThreat[] = [
  {
    id: "prox-1",
    foreignSatId: "foreign-1",
    foreignSatName: "KOSMOS 2558",
    targetAssetId: "sat-6",
    targetAssetName: "USA-281",
    severity: "threatened",
    missDistanceKm: 0.8,
    approachVelocityKms: 0.014,
    tcaTime: Date.now() + 1200000,
    tcaInMinutes: 20,
    primaryPosition: { lat: 35.2, lon: -42.8, altKm: 500 },
    secondaryPosition: { lat: 35.5, lon: -42.3, altKm: 502 },
    approachPattern: "co-orbital",
    sunHidingDetected: true,
    confidence: 0.93,
  },
  {
    id: "prox-2",
    foreignSatId: "foreign-2",
    foreignSatName: "SJ-21",
    targetAssetId: "sat-14",
    targetAssetName: "WGS-10",
    severity: "watched",
    missDistanceKm: 18.5,
    approachVelocityKms: 0.008,
    tcaTime: Date.now() + 5400000,
    tcaInMinutes: 90,
    primaryPosition: { lat: -0.1, lon: 78.5, altKm: 35790 },
    secondaryPosition: { lat: -0.2, lon: 79.2, altKm: 35786 },
    approachPattern: "drift",
    sunHidingDetected: false,
    confidence: 0.71,
  },
  {
    id: "prox-3",
    foreignSatId: "foreign-3",
    foreignSatName: "SHIJIAN-17",
    targetAssetId: "sat-4",
    targetAssetName: "SENTINEL-2A",
    severity: "nominal",
    missDistanceKm: 120.0,
    approachVelocityKms: 0.003,
    tcaTime: Date.now() + 14400000,
    tcaInMinutes: 240,
    primaryPosition: { lat: 52.3, lon: -95.7, altKm: 790 },
    secondaryPosition: { lat: 51.9, lon: -94.8, altKm: 786 },
    approachPattern: "direct",
    sunHidingDetected: false,
    confidence: 0.55,
  },
]

// ── Signal Interception ──

export const MOCK_SIGNAL_THREATS: SignalThreat[] = [
  {
    id: "sig-1",
    interceptorId: "foreign-4",
    interceptorName: "LUCH / OLYMP-K",
    targetLinkAssetId: "sat-1",
    targetLinkAssetName: "ISS (ZARYA)",
    groundStationName: "Buckley SFB",
    severity: "watched",
    interceptionProbability: 0.34,
    signalPathAngleDeg: 12.4,
    commWindowsAtRisk: 3,
    totalCommWindows: 14,
    tcaTime: Date.now() + 3600000,
    tcaInMinutes: 60,
    position: { lat: 39.7, lon: -104.8, altKm: 35786 },
    confidence: 0.68,
  },
  {
    id: "sig-2",
    interceptorId: "foreign-5",
    interceptorName: "TJS-3",
    targetLinkAssetId: "sat-5",
    targetLinkAssetName: "LANDSAT 8",
    groundStationName: "Schriever SFB",
    severity: "nominal",
    interceptionProbability: 0.12,
    signalPathAngleDeg: 28.9,
    commWindowsAtRisk: 1,
    totalCommWindows: 22,
    tcaTime: Date.now() + 7200000,
    tcaInMinutes: 120,
    position: { lat: 38.8, lon: -104.5, altKm: 35400 },
    confidence: 0.45,
  },
  {
    id: "sig-3",
    interceptorId: "foreign-7",
    interceptorName: "COSMOS 2542",
    targetLinkAssetId: "sat-3",
    targetLinkAssetName: "AQUA",
    groundStationName: "Pine Gap, AUS",
    severity: "threatened",
    interceptionProbability: 0.61,
    signalPathAngleDeg: 5.8,
    commWindowsAtRisk: 5,
    totalCommWindows: 18,
    tcaTime: Date.now() + 1800000,
    tcaInMinutes: 30,
    position: { lat: -23.8, lon: 133.7, altKm: 450 },
    confidence: 0.88,
  },
  {
    id: "sig-4",
    interceptorId: "foreign-6",
    interceptorName: "YAOGAN-30D",
    targetLinkAssetId: "sat-7",
    targetLinkAssetName: "HUBBLE SPACE TELESCOPE",
    groundStationName: "RAF Menwith Hill",
    severity: "watched",
    interceptionProbability: 0.28,
    signalPathAngleDeg: 18.2,
    commWindowsAtRisk: 2,
    totalCommWindows: 16,
    tcaTime: Date.now() + 5400000,
    tcaInMinutes: 90,
    position: { lat: 54.0, lon: -1.7, altKm: 600 },
    confidence: 0.59,
  },
  {
    id: "sig-5",
    interceptorId: "foreign-2",
    interceptorName: "SJ-21",
    targetLinkAssetId: "sat-4",
    targetLinkAssetName: "SENTINEL-2A",
    groundStationName: "Kaena Point, HI",
    severity: "nominal",
    interceptionProbability: 0.09,
    signalPathAngleDeg: 34.7,
    commWindowsAtRisk: 1,
    totalCommWindows: 20,
    tcaTime: Date.now() + 10800000,
    tcaInMinutes: 180,
    position: { lat: 21.6, lon: -158.2, altKm: 35786 },
    confidence: 0.38,
  },
]

// ── Satellite Hijacking & Anomalous Behavior ──

export const MOCK_ANOMALY_THREATS: AnomalyThreat[] = [
  {
    id: "anom-1",
    satelliteId: "foreign-1",
    satelliteName: "KOSMOS 2558",
    severity: "threatened",
    anomalyType: "unexpected-maneuver",
    baselineDeviation: 0.87,
    description: "Executed 0.4 m/s prograde burn not consistent with station-keeping. New orbit reduces miss distance with USA-281.",
    detectedAt: Date.now() - 600000,
    confidence: 0.91,
    position: { lat: 33.8, lon: -44.2, altKm: 498 },
  },
  {
    id: "anom-2",
    satelliteId: "foreign-6",
    satelliteName: "YAOGAN-30D",
    severity: "watched",
    anomalyType: "pointing-change",
    baselineDeviation: 0.52,
    description: "Antenna pattern redirected 15\u00b0 from nadir. Now aligned with NOAA-20 orbital plane.",
    detectedAt: Date.now() - 1800000,
    confidence: 0.74,
    position: { lat: 8.2, lon: 112.5, altKm: 600 },
  },
  {
    id: "anom-3",
    satelliteId: "foreign-7",
    satelliteName: "COSMOS 2542",
    severity: "watched",
    anomalyType: "orbit-raise",
    baselineDeviation: 0.41,
    description: "Apogee raised 12 km over last 48 hrs. Trajectory converging with HUBBLE SPACE TELESCOPE orbital shell.",
    detectedAt: Date.now() - 3600000,
    confidence: 0.63,
    position: { lat: -22.4, lon: 56.8, altKm: 545 },
  },
]

// ── Orbital Similarity ──

export const MOCK_ORBITAL_SIMILARITY_THREATS: OrbitalSimilarityThreat[] = [
  {
    id: "osim-1",
    foreignSatId: "foreign-1",
    foreignSatName: "KOSMOS 2558",
    targetAssetId: "sat-6",
    targetAssetName: "USA-281",
    severity: "threatened",
    inclinationDiffDeg: 0.4,
    altitudeDiffKm: 3.2,
    divergenceScore: 0.007,
    pattern: "co-planar",
    confidence: 0.94,
    position: { lat: 35.2, lon: -42.8, altKm: 501 },
  },
  {
    id: "osim-2",
    foreignSatId: "foreign-2",
    foreignSatName: "SJ-21",
    targetAssetId: "sat-14",
    targetAssetName: "WGS-10",
    severity: "watched",
    inclinationDiffDeg: 3.1,
    altitudeDiffKm: 18.0,
    divergenceScore: 0.071,
    pattern: "co-inclination",
    confidence: 0.68,
    position: { lat: -0.1, lon: 78.5, altKm: 35800 },
  },
  {
    id: "osim-3",
    foreignSatId: "foreign-3",
    foreignSatName: "SHIJIAN-17",
    targetAssetId: "sat-4",
    targetAssetName: "SENTINEL-2A",
    severity: "nominal",
    inclinationDiffDeg: 7.2,
    altitudeDiffKm: 65.0,
    divergenceScore: 0.21,
    pattern: "shadowing",
    confidence: 0.41,
    position: { lat: 52.3, lon: -95.7, altKm: 790 },
  },
]
